### ISSUE TITLE
Using the SparkFun LSM6DS3 library

### ISSUE THREAD

**Issue by mfreema5** [ostaquet/Arduino-Nano-33-IoT-Ultimate-Guide#2]
You can use the much more extensive [LSM6DS3 library from SparkFun](https://github.com/sparkfun/SparkFun_LSM6DS3_Arduino_Library) with the Nano 33 IoT.  You simply need to change the I2C address of the LSM6DS3.  For example, in the SparkFun “[MinimalistExample](https://github.com/sparkfun/SparkFun_LSM6DS3_Arduino_Library/blob/master/examples/MinimalistExample/MinimalistExample.ino)” sketch, change `LSM6DS3 myIMU;` to

    LSM6DS3 myIMU(I2C_MODE, 0x6A);

**Comment by ostaquet** [comment]
Thanks for the sharing. Indeed this library is more complete ;-) It is in the guide now.
