### ISSUE TITLE
Touching port COM6 at 1200bps

### ISSUE THREAD

**Issue by cr8myf8** [ostaquet/Arduino-Nano-33-IoT-Ultimate-Guide#3]
When I am using the Arduino Editor Web IDE it get stuck 

The sketch compiles then ...

"Programming with: Serial

Restarting in bootloader mode

Get port list before reset

[COM6]

Touching port COM6 at 1200bps"

And it just hangs with out programming the device.  

Any ideas?

**Comment by ostaquet** [comment]
Hi @cr8myf8,

I have no experience with the Arduino Web Editor and cannot help on this.

I suggest to go on forum or contact directly Arduino support for this.

KR,
Olivier
