### ISSUE TITLE
Wifi problems when powered from VIN

### ISSUE THREAD

**Issue by pavelsmak** [ostaquet/Arduino-Nano-33-IoT-Ultimate-Guide#5]
Hello, 

there is an issue with Wifi module when the board is powered through VIN. It seems that supplying the board with 5V through VIN is not enough for stable operation of the board. When the Wifi module is active (with 5V on VIN), the digital output pins switch to undefined states (such as 0.96 V with digitalWrite LOW).

The issue was observed when the board was connected to Arduino IoT Cloud. I did not test with higher voltages on VIN, nonetheless, powering the board with USB resolved all these problems. It has already been partially discussed elsewhere (https://forum.arduino.cc/index.php?topic=624569.msg4301900#msg4301900), however, it would be nice to point this out also in the guide.

**Comment by ostaquet** [comment]
This is a very interesting discussion and I will be happy to exchange with you.

I experienced some stability issues in one of my project. Supplying power through the VIN seems to cause some instability when the Wifi is running. I guessed it was related to the consumption of the radio chipset (which is well know as a power consumer).

I participated in the topic of the forum you mentioned and made my own experiments...

According to the box of the Arduino Nano 33 IoT, the input voltages are:
* Input - USB : 5V
* Input - VIN : 4.5V - 21V
* Operating: 3.3V

When checking [the datasheet of the embedded converter (MPM3610)](https://www.monolithicpower.com/en/documentview/productdocument/index/version/2/document_type/Datasheet/lang/en/sku/MPM3610GQV/document_id/2090), the operating range of VIN seems to be confirmed.

The tests I made are described on the main page and the source codes are in the repository. I always tested the behavior based on the program alone and no external peripherals to avoid perturbations.

The conclusion of those tests is that the Arduino Nano 33 IoT can be powered from VIN between 4.5V and 21V without any incidences when Wifi is running.

I'll be happy to discuss about the unexpected behaviors you noticed to have a better view and explain this in details together to the others who are interested.
