### ISSUE TITLE
About the ultimate power save mode

### ISSUE THREAD

**Issue by JoshYang1977** [ostaquet/Arduino-Nano-33-IoT-Ultimate-Guide#6]
Hello, 

I follow your recommendation and set up the RTC and others with Arduino 33 IoT.
When it is implemented, the power only goes through RTC clock (LED in on) but Arduino is not.

If I disconnect the SQW from RTC, both LEDs are on.
Do you know what is happening? 

Thank you very much for your time and answer.

**Comment by ostaquet** [comment]
Hi @JoshYang1977,

It seems that your DS3231 is not properly initialized. It is important to setup the registers of the DS3231 before using the power save mode and wake up on interrupt by the DS3231. If not, your Arduino will never be woke up by the interrupt.

KR,
Olivier

**Comment by jandrassy** [comment]
https://electronics.stackexchange.com/questions/573121/how-can-mosfet-drain-be-used-as-ground-for-a-load

**Comment by ostaquet** [comment]
Thanks for the feedback @jandrassy, the schematics have been updated based on the advices. The schematic has been simplified and a P-channel MOSFET has been used on the high-side with pull-down resistor to be more sharp on the voltage.
