### ISSUE TITLE
Power saving, how to turn off modules

### ISSUE THREAD

**Issue by Cellule** [ostaquet/Arduino-Nano-33-IoT-Ultimate-Guide#7]
In the section for power saving mode, it says

> Shutdown all useless components (Wifi, IMU...)

However I can't find how I can turn off modules before going to sleep.
Right now I disconnect the wifi and put it to `lowPowerMode` and I use `Arduino Low Power`'s `sleep` method with an RTC interrupt for wake. 
(Side-note, comparing the implementation of ArduinoLowPower and Adafruit SleepyDog for the nano-33-iot they look very very similar except one uses RTC for wake and the other uses the watchdog)

I only really need to take 1 measurement per 30mins and send that over wifi. The whole operation takes ~5s. 
I don't have a good way to measure how much current is being used while on sleep, but my batteries are getting tanked.

I am starting to consider an external RTC clock to control power but I was hoping to find a suitable software solution before adding more components to my circuit.

**Comment by ostaquet** [comment]
If you didn't initialise some components (Wifi, IMU...), you have nothing to do.
If you initialise them, you should stop properly the components. Per example, the WiFiNINA library offers the `WiFi.end()` to stop all activities. The `WiFi.lowPowerMode()` is used only when you are operating to limit the power drain.

As your operation is around 5 seconds every 30 minutes, the low power mode for the wifi is not so useful; except if you have very small batteries that cannot support 100mA of current drain (like solar panels).

The usage of the sleep method of the ArduinoLowPower lib will still drain 6mA to do nothing. It means that with a standard battery of 1600mA (AA cells), you can live 10 days by doing nothing (if you don't lose any other power in other components).

I suggest to use the external RTC with a full shutdown of the MCU. The power on is controlled by the external RTC clock (living on a CR2032 lithium button cell for 4-5 years). The power off is requested by the MCU when the operation is over. The biggest advantage is that your MCU will consume 0mA. So, your battery of 1600mA (AA cells) will live as long as your real workload.

See https://github.com/ostaquet/Arduino-Nano-33-IoT-Ultimate-Guide/blob/master/SavePowerRTC.md for the details.

**Comment by Cellule** [comment]
Thanks! I was indeed using `WiFi.lowPowerMode()` instead of `WiFi.end()` so this must have been a big offender, but like you mentioned it prolly won't make a huge difference.

I'll start looking into using an external RTC for a full shutdown. Last time I checked I had trouble finding the right parts or wasn't sure how to tweak the system for slightly different parts.
I'm more a software person so I'm way more on the beginner's side when it comes to electrical circuit.
That being said thank you so much for providing all these examples
