### ISSUE TITLE
Max current 5V

### ISSUE THREAD

**Issue by acklenx** [ostaquet/Arduino-Nano-33-IoT-Ultimate-Guide#9]
If you enable the 5V pin, you don't state what the max current available is.

**Comment by ostaquet** [comment]
When you solder the VUSB jumper, you enable the 5V pin. This pin is mainly use for compatibility purpose and it is a direct link from the USB.

It means also that the 5V is powered only when the USB is connected. If you power the Nano through the Vin, the 5V will not be powered.

![Screenshot 2021-06-28 at 11 12 20](https://user-images.githubusercontent.com/28394361/123611572-06c46300-d802-11eb-87cc-2e6eb17dc80f.png)

There is no specific circuitry for the 5V. So, the max current available is the max current provided by the USB source (your laptop or the power bank).

![Screenshot 2021-06-28 at 11 11 11](https://user-images.githubusercontent.com/28394361/123611607-0fb53480-d802-11eb-8bdc-4f996be689d5.png)

**Comment by acklenx** [comment]
> ![Screenshot 2021-06-28 at 11 12 20](https://user-images.githubusercontent.com/28394361/123611572-06c46300-d802-11eb-87cc-2e6eb17dc80f.png)
> 
> There is no specific circuitry for the 5V. So, the max current available is the max current provided by the USB source (your laptop or the power bank).
> 

Wait... If there is a Schottky diode, and it is a PMEG6020 (sounds pretty specific), then wouldn't the current be limited to 2 amps?!

Either way, calling out the current is what I was hoping you would do in your very excellent write up. 

If someone (me) is testing with servos (9g) attached, and expecting usb power to work it's go to know for sure they are out are not going to put either $30 Arduino or their $$$ computer at risk.

**Comment by ostaquet** [comment]
The PMEG6020 is only there to avoid VIN current to go to VUSB.

When you power up the Nano through the USB and solder the VUSB jumper, you should be able to power up additional sensors or servos without damaging your computer and the Nano. But...

Most of computers are able to provide 0.5A or 0.9A of current through USB ports. So, I do not recommend to power up too much stuff through this channel.
